version: '3'

services:
  db:
    image: postgres:10.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  platform:
    build:
      context: .
      dockerfile: platform/Dockerfile
    restart: unless-stopped
    ports:
      - 9092:9092
    volumes:
      - ./data:/data:z
    env_file:
      - ./conf/common.env

  ab:
    build:
      context: apache-benchmark
    command: ab -n 100 -c 10 go:8080/hosts/1

  python:
    build:
      context: .
      dockerfile: ./prototypes/py/Dockerfile
    depends_on:
      - db
      - platform
    image: spm/prototype-py:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./data:/data:z
    env_file:
      - ./conf/common.env

  go:
    build:
      context: ./prototypes/go
      dockerfile: Dockerfile
    environment:
      GOPATH: /go

      PRIVATE_API_USER: admin
      PRIVATE_API_PASSWD: passwd

      GIN_MODE: release
      LOG_LEVEL: debug
      LOG_STYLE: json

    env_file:
      - ./conf/common.env
    volumes:
      - ./prototypes/go/app:/go/src/gin-container/app
    command: go run -v main.go --listener
    ports:
      - 8080:8080
    depends_on:
      - db
      - platform
